import type { Responsabilidade } from "./tipos";

/** O que cada posição faz. Separado da estrutura para permitir reescrever
 * missão e escopo sem mexer no organograma. Prompts completos dos agentes não
 * moram aqui - serão conectados depois, por posição. `assuntos` alimenta a
 * busca "quem cuida de...", então use as palavras que Vinícius usaria. */
const r = (missao: string, responsabilidades: string[], assuntos: string[], resultados: string[]): Responsabilidade => ({
  missao, responsabilidades, assuntos, resultados,
});

export const RESPONSABILIDADES: Record<string, Responsabilidade> = {
  ceo: r("Definir para onde a Zatti vai e decidir o que só o dono pode decidir.",
    ["Metas e limites", "Decisões estratégicas e exceções", "Aprovar o que o Vini leva para decisão"],
    ["estratégia", "meta", "decisão", "sociedade", "investimento"],
    ["Meta de faturamento acompanhada", "Decisões registradas"]),
  "chefe-operacoes": r("Receber todo pedido de Vinícius e encaminhar para a sala certa, acompanhando até a entrega.",
    ["Recepção dos pedidos", "Distribuir trabalho entre as diretorias", "Acompanhar prazos e cobrar entregas", "Consolidar o estado global e levar exceções a Vinícius"],
    ["agenda", "prioridade", "pedido", "encaminhar", "cobrança", "rotina", "dia"],
    ["Agenda do dia organizada", "Pedidos encaminhados sem Vinícius decorar quem faz o quê", "Pendências visíveis"]),

  "dir-vendas": r("Garantir fluxo previsível de novos clientes para a Zatti.",
    ["Coordenar Marketing e Comercial", "Definir metas de aquisição", "Acompanhar funil e conversão"],
    ["vendas", "funil", "aquisição", "meta comercial"],
    ["Funil com números reais", "Clientes novos por mês"]),
  marketing: r("Gerar atenção e demanda qualificada para a Zatti.",
    ["Conteúdo do Instagram", "Posicionamento e marca", "Campanhas e captação de leads"],
    ["instagram", "conteúdo", "carrossel", "reels", "marca", "campanha", "lead"],
    ["Calendário de conteúdo cumprido", "Leads gerados"]),
  comercial: r("Transformar oportunidades em contratos fechados.",
    ["Operação Zatti com o Grupo Silva", "Prospecção e pesquisa de prospectos", "Propostas", "Follow-up e fechamento"],
    ["grupo silva", "antonio", "prospecção", "proposta", "negociação", "fechamento", "follow-up", "pipeline"],
    ["Propostas enviadas", "Contratos fechados"]),

  "dir-clientes": r("Garantir que cada cliente da Zatti seja implantado, atendido e renove.",
    ["Coordenar Implantação, Consultoria, BPO e Sucesso do Cliente", "Acompanhar a saúde da carteira"],
    ["cliente", "carteira", "atendimento", "renovação"],
    ["Carteira sem cliente esquecido", "Renovações"]),
  implantacao: r("Colocar o cliente novo para rodar com o método e o Zatti Hub.",
    ["Onboarding", "Cadastro e ajustes de dados no Zatti Hub", "Treinamento da equipe do cliente"],
    ["onboarding", "implantação", "cadastro", "produtos", "treinamento"],
    ["Cliente operando no Zatti Hub", "Dados iniciais corretos"]),
  "consultoria-mega": r("Conduzir a consultoria pelo método M.E.G.A.",
    ["Reuniões de consultoria", "Diagnóstico e plano de ação", "Documento Mestre do cliente"],
    ["consultoria", "m.e.g.a.", "mega", "reunião", "diagnóstico", "documento mestre"],
    ["Fases do M.E.G.A. avançando", "Decisões do cliente registradas"]),
  "bpo-financeiro": r("Manter o financeiro dos clientes de BPO em dia e confiável.",
    ["Extratos e conciliação", "DRE mensal", "Contas a pagar e receber dos clientes"],
    ["bpo", "extrato", "conciliação", "dre", "contas a pagar", "fluxo de caixa do cliente"],
    ["DRE fechada no prazo", "Conciliação sem pendência"]),
  "sucesso-cliente": r("Garantir que o cliente perceba resultado e continue.",
    ["Acompanhamento pós-implantação", "Sinais de risco de cancelamento", "Pesquisa de satisfação"],
    ["satisfação", "cancelamento", "retenção", "relacionamento"],
    ["Retenção", "Riscos detectados antes do cancelamento"]),

  "dir-produto": r("Decidir o que a Zatti constrói e garantir que funciona.",
    ["Coordenar Zatti Hub, Produtos Digitais, Automações e Dados", "Priorizar a fila de construção"],
    ["produto", "tecnologia", "roadmap", "fila de construção"],
    ["Fila priorizada", "Entregas no ar sem regressão"]),
  "zatti-hub": r("Evoluir e manter o Zatti Hub.",
    ["Módulos e correções do app", "Segurança e backup", "Publicação"],
    ["zatti hub", "app", "sistema", "bug", "estoque", "cotação", "financeiro gerencial"],
    ["Módulos no ar e testados", "Backup diário funcionando"]),
  "produtos-digitais": r("Criar e vender produtos digitais da Zatti.",
    ["Livro M.E.G.A.", "Planilhas e cursos", "Páginas de venda e lançamentos"],
    ["livro", "planilha", "curso", "kiwify", "lançamento", "página de vendas"],
    ["Produtos publicados", "Vendas digitais"]),
  automacoes: r("Automatizar o que já foi validado manualmente.",
    ["Automações de WhatsApp, agenda e rotinas", "Manutenção do Vini e integrações"],
    ["automação", "whatsapp", "integração", "robô"],
    ["Horas manuais eliminadas", "Automações sem falha silenciosa"]),
  dados: r("Transformar dados em leitura clara para decisão.",
    ["Indicadores", "Painéis", "Análises de vendas e cardápio"],
    ["indicador", "painel", "dados", "curva abc", "análise"],
    ["Indicadores confiáveis", "Análises entregues"]),

  "dir-corporativa": r("Manter a Zatti organizada, legal e financeiramente saudável.",
    ["Coordenar Financeiro, Jurídico, Processos e Melhoria Contínua"],
    ["administrativo", "corporativo", "governança"],
    ["Empresa em dia", "Riscos corporativos visíveis"]),
  "financeiro-zatti": r("Cuidar do caixa e do resultado da própria Zatti.",
    ["Fluxo de caixa da Zatti", "Recebimentos de clientes", "Provisões e resultado"],
    ["caixa da zatti", "faturamento", "recebimento", "provisão", "resultado da zatti"],
    ["Caixa conhecido", "Faturamento contra a meta"]),
  juridico: r("Proteger a Zatti em contratos e acordos.",
    ["Contratos de clientes", "Termos e acordos", "Revisão de riscos jurídicos"],
    ["contrato", "jurídico", "termo", "aditivo", "rescisão"],
    ["Contratos assinados", "Nenhum serviço sem contrato"]),
  processos: r("Documentar como a Zatti trabalha e garantir o padrão.",
    ["Mapeamento de processos", "Checklists e padrões", "Auditoria de qualidade"],
    ["processo", "padrão", "checklist", "qualidade"],
    ["Processos documentados", "Menos retrabalho"]),
  "melhoria-continua": r("Fazer erro recorrente virar regra e parar de acontecer.",
    ["Registrar aprendizados", "Transformar correções em regra", "Revisar gargalos"],
    ["aprendizado", "erro recorrente", "melhoria", "gargalo"],
    ["Erros que não se repetem", "Regras aplicadas"]),

  "hzz-cmo": r("Responder pelo crescimento e pela estratégia de marketing da Horizzon.",
    ["Estratégia da Horizzon", "Decisões sobre clientes Horizzon", "Aprovar entregas críticas"],
    ["horizzon", "cmo", "estratégia horizzon"],
    ["Clientes Horizzon com resultado", "Crescimento da Horizzon"]),
  "hzz-coordenacao": r("Coordenar a operação da Horizzon sem misturar com a Zatti.",
    ["Encaminhar demandas da Horizzon", "Acompanhar reuniões e prazos", "Avisos aos grupos dos clientes Horizzon"],
    ["horizzon", "operação horizzon", "cliente horizzon", "grupo do cliente"],
    ["Demandas da Horizzon encaminhadas", "Prazos acompanhados"]),
  "hzz-estrategia": r("Definir a estratégia de conteúdo de cada cliente da Horizzon.",
    ["Pauta mensal", "Análise de perfil e referências", "Direção de captação e edição"],
    ["pauta", "estratégia de conteúdo", "análise de perfil", "referências", "captação"],
    ["Pauta aprovada no prazo"]),
  "hzz-reunioes": r("Garantir que toda reunião da Horizzon vire registro e ação.",
    ["Atas", "Tarefas das reuniões", "Acompanhamento dos combinados"],
    ["ata horizzon", "reunião horizzon", "onboarding horizzon", "transcrição"],
    ["Ata em até 24h", "Combinados cobrados"]),
  "hzz-relatorios": r("Mostrar o desempenho de cada cliente da Horizzon.",
    ["Relatórios mensais", "Métricas de conteúdo e tráfego"],
    ["relatório horizzon", "métricas", "tráfego", "desempenho"],
    ["Relatório mensal entregue"]),
  "hzz-comercial": r("Fazer a Horizzon crescer em clientes.",
    ["Prospecção da Horizzon", "Propostas e contratos da Horizzon"],
    ["venda horizzon", "proposta horizzon", "contrato horizzon"],
    ["Clientes novos da Horizzon"]),
  "hzz-entregas": r("Controlar se o time da Horizzon entrega no prazo.",
    ["Acompanhar tarefas do time", "Sinalizar atrasos"],
    ["entregas do time", "atraso", "time horizzon", "horizzon hub"],
    ["Entregas no prazo", "Atrasos sinalizados cedo"]),
};
