import type { Responsabilidade } from "./tipos";

/** O que cada posição faz. Separado da estrutura para permitir reescrever
 * missão e escopo sem mexer no organograma. Prompts completos dos agentes não
 * moram aqui - serão conectados depois, por posição. `assuntos` alimenta a
 * busca "quem cuida de...", então use as palavras que Vinícius usaria. */
const r = (missao: string, responsabilidades: string[], assuntos: string[], resultados: string[]): Responsabilidade => ({
  missao, responsabilidades, assuntos, resultados,
});

export const RESPONSABILIDADES: Record<string, Responsabilidade> = {
  ceo: r("Definir para onde a Zatti vai e decidir o que só o dono pode decidir.",
    ["Metas e limites", "Decisões estratégicas e exceções", "Aprovar o que o Vini leva para decisão"],
    ["estratégia", "meta", "decisão", "sociedade", "investimento"],
    ["Meta de faturamento acompanhada", "Decisões registradas"]),
  "chefe-operacoes": r("Receber todo pedido de Vinícius e encaminhar para a sala certa, acompanhando até a entrega.",
    ["Recepção dos pedidos", "Distribuir trabalho entre as diretorias", "Acompanhar prazos e cobrar entregas", "Consolidar o estado global e levar exceções a Vinícius"],
    ["agenda", "prioridade", "pedido", "encaminhar", "cobrança", "rotina", "dia"],
    ["Agenda do dia organizada", "Pedidos encaminhados sem Vinícius decorar quem faz o quê", "Pendências visíveis"]),

  "dir-vendas": r("Garantir fluxo previsível de novos clientes para a Zatti.",
    ["Coordenar Marketing e Comercial", "Definir metas de aquisição", "Acompanhar funil e conversão"],
    ["vendas da zatti", "vendas", "funil", "aquisição", "meta comercial"],
    ["Funil com números reais", "Clientes novos por mês"]),
  marketing: r("Gerar atenção e demanda qualificada para a Zatti.",
    ["Conteúdo do Instagram", "Posicionamento e marca", "Campanhas e captação de leads"],
    ["instagram", "conteúdo", "carrossel", "reels", "marca", "campanha", "lead"],
    ["Calendário de conteúdo cumprido", "Leads gerados"]),
  comercial: r("Transformar oportunidades em contratos fechados.",
    ["Operação Zatti com o Grupo Silva", "Prospecção e pesquisa de prospectos", "Propostas", "Follow-up e fechamento"],
    ["grupo silva", "antonio", "prospecção", "proposta", "negociação", "fechamento", "follow-up", "pipeline"],
    ["Propostas enviadas", "Contratos fechados"]),

  "autoridade-tecnica": r("Ser a fonte do conhecimento de restaurante da Zatti e guardar o Método M.E.G.A.",
    ["Responder pelo método em todas as áreas de restaurante", "Validar orientações novas antes de virarem M.E.G.A.", "Nunca deixar opinião de concorrente ocupar o lugar do método"],
    ["m.e.g.a.", "mega", "método", "restaurante", "gestão de restaurante", "livro"],
    ["Clientes com resultado pelo método", "Orientações validadas incorporadas ao M.E.G.A."]),
  "coordenacao-clientes": r("Coordenar a carteira e preparar o terreno para o trabalho de Vinícius.",
    ["Carteira e atendimento", "Onboarding e implantação", "Cadastro e ajustes de dados no Zatti Hub"],
    ["cliente", "carteira", "atendimento", "onboarding", "implantação", "cadastro", "treinamento"],
    ["Cliente operando no Zatti Hub", "Carteira sem cliente esquecido"]),
  "diagnostico-mega": r("Diagnosticar o restaurante pelo Método M.E.G.A.",
    ["Diagnóstico inicial", "Plano de ação", "Documento Mestre do cliente"],
    ["diagnóstico", "consultoria", "documento mestre", "reunião de consultoria", "plano de ação"],
    ["Diagnóstico entregue", "Decisões do cliente registradas"]),
  "bpo-financeiro": r("Definir como o financeiro do restaurante é gerido, pelo método de Vinícius.",
    ["Metodologia de DRE e fluxo de caixa do cliente", "Leitura do resultado com o cliente"],
    ["bpo", "dre", "extrato", "conciliação", "fluxo de caixa do cliente", "financeiro do restaurante"],
    ["DRE fechada no prazo", "Cliente entende o próprio resultado"]),
  "bpo-execucao": r("Executar a rotina de BPO dentro da metodologia de Vinícius.",
    ["Extratos e conciliação", "Montagem da DRE mensal", "Contas a pagar e receber dos clientes"],
    ["extrato", "conciliação", "contas a pagar", "lançamentos"],
    ["Conciliação sem pendência"]),
  "cmv-estoque": r("Controlar CMV, estoque e compras do restaurante.",
    ["Inventário e contagem", "Fichas e CMV", "Cotação e compras"],
    ["cmv", "estoque", "inventário", "contagem", "compras", "cotação", "fornecedor"],
    ["CMV conhecido", "Estoque contado no prazo"]),
  precificacao: r("Definir preços que sustentam a margem do restaurante.",
    ["Custo por ficha técnica", "Formação de preço", "Revisão de preços"],
    ["precificação", "preço", "ficha técnica", "margem", "markup"],
    ["Preços com margem conhecida"]),
  "engenharia-cardapio": r("Fazer o cardápio vender o que dá resultado.",
    ["Curva ABC", "Mix e margem por item", "Ajustes no cardápio"],
    ["cardápio", "curva abc", "mix", "engenharia de cardápio"],
    ["Cardápio revisado com dado de venda e margem"]),
  "vendas-restaurante": r("Aumentar as vendas do restaurante cliente.",
    ["Leitura das vendas do salão e do delivery", "Ações para vender mais"],
    ["vendas do restaurante", "faturamento do restaurante", "ifood", "delivery", "ticket médio"],
    ["Vendas do cliente em crescimento"]),
  "processos-operacao": r("Organizar a operação e a gestão da equipe do restaurante.",
    ["POPs e rotinas", "Gestão da operação e da equipe"],
    ["pop", "operação do restaurante", "rotina", "equipe do restaurante", "gestão da operação"],
    ["Operação padronizada"]),
  "sucesso-cliente": r("Garantir que o cliente perceba resultado e continue. Função ainda não definida.",
    ["A definir"],
    ["satisfação", "cancelamento", "retenção", "relacionamento"],
    ["A definir"]),

  "dir-produto": r("Decidir o que a Zatti constrói e garantir que funciona.",
    ["Coordenar Zatti Hub, Produtos Digitais, Automações e Dados", "Priorizar a fila de construção"],
    ["produto", "tecnologia", "roadmap", "fila de construção"],
    ["Fila priorizada", "Entregas no ar sem regressão"]),
  "zatti-hub": r("Evoluir e manter o Zatti Hub.",
    ["Módulos e correções do app", "Segurança e backup", "Publicação"],
    ["zatti hub", "app", "sistema", "bug", "estoque", "cotação", "financeiro gerencial"],
    ["Módulos no ar e testados", "Backup diário funcionando"]),
  "produtos-digitais": r("Criar e vender produtos digitais da Zatti.",
    ["Livro M.E.G.A.", "Planilhas e cursos", "Páginas de venda e lançamentos"],
    ["livro", "planilha", "curso", "kiwify", "lançamento", "página de vendas"],
    ["Produtos publicados", "Vendas digitais"]),
  automacoes: r("Automatizar o que já foi validado manualmente.",
    ["Automações de WhatsApp, agenda e rotinas", "Manutenção do Vini e integrações"],
    ["automação", "whatsapp", "integração", "robô"],
    ["Horas manuais eliminadas", "Automações sem falha silenciosa"]),
  dados: r("Transformar os dados da própria Zatti em leitura clara para decisão.",
    ["Indicadores", "Painéis", "Análises internas da Zatti"],
    ["indicador", "painel", "dados", "dados da zatti"],
    ["Indicadores confiáveis", "Análises entregues"]),

  "dir-corporativa": r("Manter a Zatti organizada, legal e financeiramente saudável.",
    ["Coordenar Financeiro, Jurídico, Processos e Melhoria Contínua"],
    ["administrativo", "corporativo", "governança"],
    ["Empresa em dia", "Riscos corporativos visíveis"]),
  "financeiro-zatti": r("Cuidar do caixa e do resultado da própria Zatti.",
    ["Fluxo de caixa da Zatti", "Recebimentos de clientes", "Provisões e resultado"],
    ["caixa da zatti", "faturamento", "recebimento", "provisão", "resultado da zatti"],
    ["Caixa conhecido", "Faturamento contra a meta"]),
  juridico: r("Proteger a Zatti em contratos e acordos.",
    ["Contratos de clientes", "Termos e acordos", "Revisão de riscos jurídicos"],
    ["contrato", "jurídico", "termo", "aditivo", "rescisão"],
    ["Contratos assinados", "Nenhum serviço sem contrato"]),
  processos: r("Documentar como a Zatti trabalha e garantir o padrão.",
    ["Mapeamento de processos", "Checklists e padrões", "Auditoria de qualidade"],
    ["processo", "padrão", "checklist", "qualidade"],
    ["Processos documentados", "Menos retrabalho"]),
  "melhoria-continua": r("Fazer erro recorrente virar regra e parar de acontecer.",
    ["Registrar aprendizados", "Transformar correções em regra", "Revisar gargalos"],
    ["aprendizado", "erro recorrente", "melhoria", "gargalo"],
    ["Erros que não se repetem", "Regras aplicadas"]),

  "hzz-cmo": r("Responder pelo crescimento e pela estratégia de marketing da Horizzon.",
    ["Estratégia da Horizzon", "Decisões sobre clientes Horizzon", "Aprovar entregas críticas"],
    ["horizzon", "cmo", "estratégia horizzon"],
    ["Clientes Horizzon com resultado", "Crescimento da Horizzon"]),
  "hzz-coordenacao": r("Coordenar a operação da Horizzon sem misturar com a Zatti.",
    ["Encaminhar demandas da Horizzon", "Acompanhar reuniões e prazos", "Avisos aos grupos dos clientes Horizzon"],
    ["horizzon", "operação horizzon", "cliente horizzon", "grupo do cliente"],
    ["Demandas da Horizzon encaminhadas", "Prazos acompanhados"]),
  "hzz-estrategia": r("Definir a estratégia de conteúdo de cada cliente da Horizzon.",
    ["Pauta mensal", "Análise de perfil e referências", "Direção de captação e edição"],
    ["pauta", "estratégia de conteúdo", "análise de perfil", "referências", "captação"],
    ["Pauta aprovada no prazo"]),
  "hzz-reunioes": r("Garantir que toda reunião da Horizzon vire registro e ação.",
    ["Atas", "Tarefas das reuniões", "Acompanhamento dos combinados"],
    ["ata horizzon", "reunião horizzon", "onboarding horizzon", "transcrição"],
    ["Ata em até 24h", "Combinados cobrados"]),
  "hzz-relatorios": r("Mostrar o desempenho de cada cliente da Horizzon.",
    ["Relatórios mensais", "Métricas de conteúdo e tráfego"],
    ["relatório horizzon", "métricas", "tráfego", "desempenho"],
    ["Relatório mensal entregue"]),
  "hzz-comercial": r("Fazer a Horizzon crescer em clientes.",
    ["Prospecção da Horizzon", "Propostas e contratos da Horizzon"],
    ["venda horizzon", "proposta horizzon", "contrato horizzon"],
    ["Clientes novos da Horizzon"]),
  "hzz-entregas": r("Controlar se o time da Horizzon entrega no prazo.",
    ["Acompanhar tarefas do time", "Sinalizar atrasos"],
    ["entregas do time", "atraso", "time horizzon", "horizzon hub"],
    ["Entregas no prazo", "Atrasos sinalizados cedo"]),
};
