--
-- PostgreSQL database dump
--

-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.6

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA public;


--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: consolidados_vendas; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.consolidados_vendas (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    unidade_id text NOT NULL,
    data date NOT NULL,
    credito numeric(10,2) DEFAULT 0 NOT NULL,
    debito numeric(10,2) DEFAULT 0 NOT NULL,
    pix numeric(10,2) DEFAULT 0 NOT NULL,
    dinheiro numeric(10,2) DEFAULT 0 NOT NULL,
    vale_alimentacao numeric(10,2) DEFAULT 0 NOT NULL,
    salao numeric(10,2) DEFAULT 0 NOT NULL,
    delivery_proprio numeric(10,2) DEFAULT 0 NOT NULL,
    ifood numeric(10,2) DEFAULT 0 NOT NULL,
    food99 numeric(10,2) DEFAULT 0 NOT NULL,
    total_formas_pagamento numeric(10,2) NOT NULL,
    total_canais numeric(10,2) NOT NULL,
    total_marketplaces numeric(10,2) NOT NULL,
    faturamento_total numeric(10,2) NOT NULL,
    diferenca numeric(10,2) NOT NULL,
    status text NOT NULL,
    criado_por uuid NOT NULL,
    criado_em timestamp with time zone DEFAULT now() NOT NULL,
    atualizado_por uuid,
    atualizado_em timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT consolidados_vendas_status_check CHECK ((status = ANY (ARRAY['conferido'::text, 'divergente'::text])))
);


--
-- Name: contagem_itens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.contagem_itens (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    contagem_id uuid NOT NULL,
    ordem bigint NOT NULL,
    origem_linha_planilha integer,
    sku text NOT NULL,
    grupo text DEFAULT ''::text NOT NULL,
    nome text DEFAULT ''::text NOT NULL,
    unidade_base text DEFAULT ''::text NOT NULL,
    quantidade numeric,
    preco_unitario numeric,
    total numeric,
    alerta text DEFAULT ''::text NOT NULL,
    criado_em timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: contagem_itens_ordem_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.contagem_itens ALTER COLUMN ordem ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contagem_itens_ordem_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: contagens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.contagens (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    unidade_id text NOT NULL,
    data date NOT NULL,
    mes text NOT NULL,
    criado_por uuid,
    criado_em timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: fornecedores; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.fornecedores (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    unidade_id text NOT NULL,
    ordem bigint NOT NULL,
    codigo text NOT NULL,
    razao_social text DEFAULT ''::text NOT NULL,
    nome_fantasia text DEFAULT ''::text NOT NULL,
    grupos text[] DEFAULT '{}'::text[] NOT NULL,
    nome_vendedor text DEFAULT ''::text NOT NULL,
    whatsapp text DEFAULT ''::text NOT NULL,
    condicoes_pagamento text DEFAULT ''::text NOT NULL,
    prazo_boleto text DEFAULT ''::text NOT NULL,
    limite_credito numeric,
    pedido_minimo numeric,
    dias_entrega text DEFAULT ''::text NOT NULL,
    observacoes text DEFAULT ''::text NOT NULL,
    criado_em timestamp with time zone DEFAULT now() NOT NULL,
    atualizado_em timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: fornecedores_ordem_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.fornecedores ALTER COLUMN ordem ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.fornecedores_ordem_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: logs_auditoria; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.logs_auditoria (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    unidade_id text NOT NULL,
    user_id uuid NOT NULL,
    acao text NOT NULL,
    entidade text NOT NULL,
    entidade_id text NOT NULL,
    dados_antigos jsonb,
    dados_novos jsonb,
    criado_em timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: organizacoes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.organizacoes (
    id text NOT NULL,
    nome text NOT NULL,
    tipo_cliente text NOT NULL,
    ativo boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT organizacoes_tipo_cliente_check CHECK ((tipo_cliente = ANY (ARRAY['consultoria'::text, 'saas'::text, 'hybrid'::text])))
);


--
-- Name: pedido_itens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.pedido_itens (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    pedido_id uuid NOT NULL,
    sku text NOT NULL,
    nome text NOT NULL,
    nome_compra text,
    unidade_base text NOT NULL,
    quantidade_pedida numeric NOT NULL,
    quantidade_recebida numeric,
    preco_antigo numeric,
    preco_atualizado numeric,
    preco_confirmado boolean DEFAULT false NOT NULL,
    vencedor_confirmado boolean DEFAULT false NOT NULL
);


--
-- Name: pedidos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.pedidos (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    unidade_id text NOT NULL,
    fornecedor text NOT NULL,
    data_contagem_base text NOT NULL,
    previsao_entrega date,
    observacao_entrega text,
    recebido boolean DEFAULT false NOT NULL,
    criado_por uuid NOT NULL,
    criado_em timestamp with time zone DEFAULT now() NOT NULL,
    atualizado_em timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: perfis; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.perfis (
    id uuid NOT NULL,
    nome text,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: produtos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.produtos (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    unidade_id text NOT NULL,
    ordem bigint NOT NULL,
    sku text NOT NULL,
    posicao numeric,
    grupo text DEFAULT ''::text NOT NULL,
    nome text DEFAULT ''::text NOT NULL,
    unidade_base text DEFAULT ''::text NOT NULL,
    preco_unitario numeric,
    estoque_necessario_semana numeric,
    estoque_minimo numeric,
    nome_compra text DEFAULT ''::text NOT NULL,
    unidade_embalagem_fornecedor text DEFAULT ''::text NOT NULL,
    qtd_unidade_base_por_embalagem numeric,
    preco_fornecedor numeric,
    fornecedor_1 text DEFAULT ''::text NOT NULL,
    fornecedor_2 text DEFAULT ''::text NOT NULL,
    fornecedor_3 text DEFAULT ''::text NOT NULL,
    fornecedor_4 text DEFAULT ''::text NOT NULL,
    observacoes text DEFAULT ''::text NOT NULL,
    ativo boolean DEFAULT true NOT NULL,
    criado_em timestamp with time zone DEFAULT now() NOT NULL,
    atualizado_em timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: produtos_ordem_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.produtos ALTER COLUMN ordem ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.produtos_ordem_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: unidades; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.unidades (
    id text NOT NULL,
    organizacao_id text NOT NULL,
    nome text NOT NULL,
    spreadsheet_id text,
    ativo boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    consolidado_vendas_habilitado boolean DEFAULT false NOT NULL,
    fonte_dados_estoque text DEFAULT 'planilha'::text NOT NULL,
    CONSTRAINT unidades_fonte_dados_estoque_check CHECK ((fonte_dados_estoque = ANY (ARRAY['planilha'::text, 'banco'::text])))
);


--
-- Name: vinculos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.vinculos (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid NOT NULL,
    organizacao_id text NOT NULL,
    unidade_id text,
    role text NOT NULL,
    status text DEFAULT 'ativo'::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT vinculos_role_check CHECK ((role = ANY (ARRAY['gestao'::text, 'operacional'::text, 'master'::text]))),
    CONSTRAINT vinculos_status_check CHECK ((status = ANY (ARRAY['convidado'::text, 'ativo'::text, 'revogado'::text])))
);


--
-- Name: consolidados_vendas consolidados_vendas_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.consolidados_vendas
    ADD CONSTRAINT consolidados_vendas_pkey PRIMARY KEY (id);


--
-- Name: consolidados_vendas consolidados_vendas_unidade_id_data_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.consolidados_vendas
    ADD CONSTRAINT consolidados_vendas_unidade_id_data_key UNIQUE (unidade_id, data);


--
-- Name: contagem_itens contagem_itens_contagem_id_origem_linha_planilha_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contagem_itens
    ADD CONSTRAINT contagem_itens_contagem_id_origem_linha_planilha_key UNIQUE (contagem_id, origem_linha_planilha);


--
-- Name: contagem_itens contagem_itens_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contagem_itens
    ADD CONSTRAINT contagem_itens_pkey PRIMARY KEY (id);


--
-- Name: contagens contagens_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contagens
    ADD CONSTRAINT contagens_pkey PRIMARY KEY (id);


--
-- Name: contagens contagens_unidade_id_data_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contagens
    ADD CONSTRAINT contagens_unidade_id_data_key UNIQUE (unidade_id, data);


--
-- Name: fornecedores fornecedores_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fornecedores
    ADD CONSTRAINT fornecedores_pkey PRIMARY KEY (id);


--
-- Name: fornecedores fornecedores_unidade_id_codigo_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fornecedores
    ADD CONSTRAINT fornecedores_unidade_id_codigo_key UNIQUE (unidade_id, codigo);


--
-- Name: logs_auditoria logs_auditoria_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.logs_auditoria
    ADD CONSTRAINT logs_auditoria_pkey PRIMARY KEY (id);


--
-- Name: organizacoes organizacoes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.organizacoes
    ADD CONSTRAINT organizacoes_pkey PRIMARY KEY (id);


--
-- Name: pedido_itens pedido_itens_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pedido_itens
    ADD CONSTRAINT pedido_itens_pkey PRIMARY KEY (id);


--
-- Name: pedidos pedidos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pedidos
    ADD CONSTRAINT pedidos_pkey PRIMARY KEY (id);


--
-- Name: pedidos pedidos_unidade_id_fornecedor_data_contagem_base_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pedidos
    ADD CONSTRAINT pedidos_unidade_id_fornecedor_data_contagem_base_key UNIQUE (unidade_id, fornecedor, data_contagem_base);


--
-- Name: perfis perfis_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.perfis
    ADD CONSTRAINT perfis_pkey PRIMARY KEY (id);


--
-- Name: produtos produtos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.produtos
    ADD CONSTRAINT produtos_pkey PRIMARY KEY (id);


--
-- Name: produtos produtos_unidade_id_sku_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.produtos
    ADD CONSTRAINT produtos_unidade_id_sku_key UNIQUE (unidade_id, sku);


--
-- Name: unidades unidades_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.unidades
    ADD CONSTRAINT unidades_pkey PRIMARY KEY (id);


--
-- Name: vinculos vinculos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vinculos
    ADD CONSTRAINT vinculos_pkey PRIMARY KEY (id);


--
-- Name: contagem_itens_contagem_ordem_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX contagem_itens_contagem_ordem_idx ON public.contagem_itens USING btree (contagem_id, ordem);


--
-- Name: contagens_unidade_data_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX contagens_unidade_data_idx ON public.contagens USING btree (unidade_id, data DESC);


--
-- Name: fornecedores_unidade_ordem_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX fornecedores_unidade_ordem_idx ON public.fornecedores USING btree (unidade_id, ordem);


--
-- Name: produtos_unidade_ordem_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX produtos_unidade_ordem_idx ON public.produtos USING btree (unidade_id, ordem);


--
-- Name: consolidados_vendas consolidados_vendas_atualizado_por_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.consolidados_vendas
    ADD CONSTRAINT consolidados_vendas_atualizado_por_fkey FOREIGN KEY (atualizado_por) REFERENCES auth.users(id);


--
-- Name: consolidados_vendas consolidados_vendas_criado_por_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.consolidados_vendas
    ADD CONSTRAINT consolidados_vendas_criado_por_fkey FOREIGN KEY (criado_por) REFERENCES auth.users(id);


--
-- Name: consolidados_vendas consolidados_vendas_unidade_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.consolidados_vendas
    ADD CONSTRAINT consolidados_vendas_unidade_id_fkey FOREIGN KEY (unidade_id) REFERENCES public.unidades(id);


--
-- Name: contagem_itens contagem_itens_contagem_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contagem_itens
    ADD CONSTRAINT contagem_itens_contagem_id_fkey FOREIGN KEY (contagem_id) REFERENCES public.contagens(id) ON DELETE CASCADE;


--
-- Name: contagens contagens_criado_por_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contagens
    ADD CONSTRAINT contagens_criado_por_fkey FOREIGN KEY (criado_por) REFERENCES auth.users(id);


--
-- Name: contagens contagens_unidade_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contagens
    ADD CONSTRAINT contagens_unidade_id_fkey FOREIGN KEY (unidade_id) REFERENCES public.unidades(id);


--
-- Name: fornecedores fornecedores_unidade_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fornecedores
    ADD CONSTRAINT fornecedores_unidade_id_fkey FOREIGN KEY (unidade_id) REFERENCES public.unidades(id);


--
-- Name: logs_auditoria logs_auditoria_unidade_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.logs_auditoria
    ADD CONSTRAINT logs_auditoria_unidade_id_fkey FOREIGN KEY (unidade_id) REFERENCES public.unidades(id);


--
-- Name: logs_auditoria logs_auditoria_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.logs_auditoria
    ADD CONSTRAINT logs_auditoria_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id);


--
-- Name: pedido_itens pedido_itens_pedido_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pedido_itens
    ADD CONSTRAINT pedido_itens_pedido_id_fkey FOREIGN KEY (pedido_id) REFERENCES public.pedidos(id) ON DELETE CASCADE;


--
-- Name: pedidos pedidos_criado_por_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pedidos
    ADD CONSTRAINT pedidos_criado_por_fkey FOREIGN KEY (criado_por) REFERENCES auth.users(id);


--
-- Name: pedidos pedidos_unidade_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pedidos
    ADD CONSTRAINT pedidos_unidade_id_fkey FOREIGN KEY (unidade_id) REFERENCES public.unidades(id);


--
-- Name: perfis perfis_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.perfis
    ADD CONSTRAINT perfis_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;


--
-- Name: produtos produtos_unidade_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.produtos
    ADD CONSTRAINT produtos_unidade_id_fkey FOREIGN KEY (unidade_id) REFERENCES public.unidades(id);


--
-- Name: unidades unidades_organizacao_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.unidades
    ADD CONSTRAINT unidades_organizacao_id_fkey FOREIGN KEY (organizacao_id) REFERENCES public.organizacoes(id);


--
-- Name: vinculos vinculos_organizacao_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vinculos
    ADD CONSTRAINT vinculos_organizacao_id_fkey FOREIGN KEY (organizacao_id) REFERENCES public.organizacoes(id);


--
-- Name: vinculos vinculos_unidade_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vinculos
    ADD CONSTRAINT vinculos_unidade_id_fkey FOREIGN KEY (unidade_id) REFERENCES public.unidades(id);


--
-- Name: vinculos vinculos_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vinculos
    ADD CONSTRAINT vinculos_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;


--
-- Name: consolidados_vendas; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.consolidados_vendas ENABLE ROW LEVEL SECURITY;

--
-- Name: consolidados_vendas consolidados_vendas_insert_por_vinculo; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY consolidados_vendas_insert_por_vinculo ON public.consolidados_vendas FOR INSERT WITH CHECK ((EXISTS ( SELECT 1
   FROM (public.vinculos v
     JOIN public.unidades u ON ((u.id = consolidados_vendas.unidade_id)))
  WHERE ((v.user_id = auth.uid()) AND (v.status = 'ativo'::text) AND ((v.role = 'master'::text) OR ((v.organizacao_id = u.organizacao_id) AND ((v.unidade_id IS NULL) OR (v.unidade_id = u.id))))))));


--
-- Name: consolidados_vendas consolidados_vendas_select_por_vinculo; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY consolidados_vendas_select_por_vinculo ON public.consolidados_vendas FOR SELECT USING ((EXISTS ( SELECT 1
   FROM (public.vinculos v
     JOIN public.unidades u ON ((u.id = consolidados_vendas.unidade_id)))
  WHERE ((v.user_id = auth.uid()) AND (v.status = 'ativo'::text) AND ((v.role = 'master'::text) OR ((v.organizacao_id = u.organizacao_id) AND ((v.unidade_id IS NULL) OR (v.unidade_id = u.id))))))));


--
-- Name: consolidados_vendas consolidados_vendas_update_por_vinculo; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY consolidados_vendas_update_por_vinculo ON public.consolidados_vendas FOR UPDATE USING ((EXISTS ( SELECT 1
   FROM (public.vinculos v
     JOIN public.unidades u ON ((u.id = consolidados_vendas.unidade_id)))
  WHERE ((v.user_id = auth.uid()) AND (v.status = 'ativo'::text) AND ((v.role = 'master'::text) OR ((v.organizacao_id = u.organizacao_id) AND ((v.unidade_id IS NULL) OR (v.unidade_id = u.id))))))));


--
-- Name: contagem_itens; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.contagem_itens ENABLE ROW LEVEL SECURITY;

--
-- Name: contagem_itens contagem_itens_insert_por_vinculo; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY contagem_itens_insert_por_vinculo ON public.contagem_itens FOR INSERT WITH CHECK ((EXISTS ( SELECT 1
   FROM ((public.contagens c
     JOIN public.unidades u ON ((u.id = c.unidade_id)))
     JOIN public.vinculos v ON (((v.user_id = auth.uid()) AND (v.status = 'ativo'::text) AND ((v.role = 'master'::text) OR ((v.organizacao_id = u.organizacao_id) AND ((v.unidade_id IS NULL) OR (v.unidade_id = u.id)))))))
  WHERE (c.id = contagem_itens.contagem_id))));


--
-- Name: contagem_itens contagem_itens_select_por_vinculo; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY contagem_itens_select_por_vinculo ON public.contagem_itens FOR SELECT USING ((EXISTS ( SELECT 1
   FROM ((public.contagens c
     JOIN public.unidades u ON ((u.id = c.unidade_id)))
     JOIN public.vinculos v ON (((v.user_id = auth.uid()) AND (v.status = 'ativo'::text) AND ((v.role = 'master'::text) OR ((v.organizacao_id = u.organizacao_id) AND ((v.unidade_id IS NULL) OR (v.unidade_id = u.id)))))))
  WHERE (c.id = contagem_itens.contagem_id))));


--
-- Name: contagem_itens contagem_itens_update_por_vinculo; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY contagem_itens_update_por_vinculo ON public.contagem_itens FOR UPDATE USING ((EXISTS ( SELECT 1
   FROM ((public.contagens c
     JOIN public.unidades u ON ((u.id = c.unidade_id)))
     JOIN public.vinculos v ON (((v.user_id = auth.uid()) AND (v.status = 'ativo'::text) AND ((v.role = 'master'::text) OR ((v.organizacao_id = u.organizacao_id) AND ((v.unidade_id IS NULL) OR (v.unidade_id = u.id)))))))
  WHERE (c.id = contagem_itens.contagem_id))));


--
-- Name: contagens; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.contagens ENABLE ROW LEVEL SECURITY;

--
-- Name: contagens contagens_insert_por_vinculo; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY contagens_insert_por_vinculo ON public.contagens FOR INSERT WITH CHECK ((EXISTS ( SELECT 1
   FROM (public.vinculos v
     JOIN public.unidades u ON ((u.id = contagens.unidade_id)))
  WHERE ((v.user_id = auth.uid()) AND (v.status = 'ativo'::text) AND ((v.role = 'master'::text) OR ((v.organizacao_id = u.organizacao_id) AND ((v.unidade_id IS NULL) OR (v.unidade_id = u.id))))))));


--
-- Name: contagens contagens_select_por_vinculo; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY contagens_select_por_vinculo ON public.contagens FOR SELECT USING ((EXISTS ( SELECT 1
   FROM (public.vinculos v
     JOIN public.unidades u ON ((u.id = contagens.unidade_id)))
  WHERE ((v.user_id = auth.uid()) AND (v.status = 'ativo'::text) AND ((v.role = 'master'::text) OR ((v.organizacao_id = u.organizacao_id) AND ((v.unidade_id IS NULL) OR (v.unidade_id = u.id))))))));


--
-- Name: fornecedores; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.fornecedores ENABLE ROW LEVEL SECURITY;

--
-- Name: fornecedores fornecedores_insert_gestao; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY fornecedores_insert_gestao ON public.fornecedores FOR INSERT WITH CHECK ((EXISTS ( SELECT 1
   FROM (public.vinculos v
     JOIN public.unidades u ON ((u.id = fornecedores.unidade_id)))
  WHERE ((v.user_id = auth.uid()) AND (v.status = 'ativo'::text) AND ((v.role = 'master'::text) OR ((v.role = 'gestao'::text) AND (v.organizacao_id = u.organizacao_id) AND ((v.unidade_id IS NULL) OR (v.unidade_id = u.id))))))));


--
-- Name: fornecedores fornecedores_select_por_vinculo; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY fornecedores_select_por_vinculo ON public.fornecedores FOR SELECT USING ((EXISTS ( SELECT 1
   FROM (public.vinculos v
     JOIN public.unidades u ON ((u.id = fornecedores.unidade_id)))
  WHERE ((v.user_id = auth.uid()) AND (v.status = 'ativo'::text) AND ((v.role = 'master'::text) OR ((v.organizacao_id = u.organizacao_id) AND ((v.unidade_id IS NULL) OR (v.unidade_id = u.id))))))));


--
-- Name: fornecedores fornecedores_update_gestao; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY fornecedores_update_gestao ON public.fornecedores FOR UPDATE USING ((EXISTS ( SELECT 1
   FROM (public.vinculos v
     JOIN public.unidades u ON ((u.id = fornecedores.unidade_id)))
  WHERE ((v.user_id = auth.uid()) AND (v.status = 'ativo'::text) AND ((v.role = 'master'::text) OR ((v.role = 'gestao'::text) AND (v.organizacao_id = u.organizacao_id) AND ((v.unidade_id IS NULL) OR (v.unidade_id = u.id))))))));


--
-- Name: logs_auditoria; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.logs_auditoria ENABLE ROW LEVEL SECURITY;

--
-- Name: logs_auditoria logs_auditoria_insert_own; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY logs_auditoria_insert_own ON public.logs_auditoria FOR INSERT WITH CHECK ((user_id = auth.uid()));


--
-- Name: organizacoes; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.organizacoes ENABLE ROW LEVEL SECURITY;

--
-- Name: organizacoes organizacoes_select_por_vinculo; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY organizacoes_select_por_vinculo ON public.organizacoes FOR SELECT USING ((EXISTS ( SELECT 1
   FROM public.vinculos v
  WHERE ((v.user_id = auth.uid()) AND (v.status = 'ativo'::text) AND ((v.role = 'master'::text) OR (v.organizacao_id = organizacoes.id))))));


--
-- Name: pedido_itens; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.pedido_itens ENABLE ROW LEVEL SECURITY;

--
-- Name: pedido_itens pedido_itens_delete_por_vinculo; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY pedido_itens_delete_por_vinculo ON public.pedido_itens FOR DELETE USING ((EXISTS ( SELECT 1
   FROM ((public.pedidos p
     JOIN public.unidades u ON ((u.id = p.unidade_id)))
     JOIN public.vinculos v ON (((v.user_id = auth.uid()) AND (v.status = 'ativo'::text) AND ((v.role = 'master'::text) OR ((v.organizacao_id = u.organizacao_id) AND ((v.unidade_id IS NULL) OR (v.unidade_id = u.id)))))))
  WHERE (p.id = pedido_itens.pedido_id))));


--
-- Name: pedido_itens pedido_itens_insert_por_vinculo; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY pedido_itens_insert_por_vinculo ON public.pedido_itens FOR INSERT WITH CHECK ((EXISTS ( SELECT 1
   FROM ((public.pedidos p
     JOIN public.unidades u ON ((u.id = p.unidade_id)))
     JOIN public.vinculos v ON (((v.user_id = auth.uid()) AND (v.status = 'ativo'::text) AND ((v.role = 'master'::text) OR ((v.organizacao_id = u.organizacao_id) AND ((v.unidade_id IS NULL) OR (v.unidade_id = u.id)))))))
  WHERE (p.id = pedido_itens.pedido_id))));


--
-- Name: pedido_itens pedido_itens_select_por_vinculo; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY pedido_itens_select_por_vinculo ON public.pedido_itens FOR SELECT USING ((EXISTS ( SELECT 1
   FROM ((public.pedidos p
     JOIN public.unidades u ON ((u.id = p.unidade_id)))
     JOIN public.vinculos v ON (((v.user_id = auth.uid()) AND (v.status = 'ativo'::text) AND ((v.role = 'master'::text) OR ((v.organizacao_id = u.organizacao_id) AND ((v.unidade_id IS NULL) OR (v.unidade_id = u.id)))))))
  WHERE (p.id = pedido_itens.pedido_id))));


--
-- Name: pedido_itens pedido_itens_update_por_vinculo; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY pedido_itens_update_por_vinculo ON public.pedido_itens FOR UPDATE USING ((EXISTS ( SELECT 1
   FROM ((public.pedidos p
     JOIN public.unidades u ON ((u.id = p.unidade_id)))
     JOIN public.vinculos v ON (((v.user_id = auth.uid()) AND (v.status = 'ativo'::text) AND ((v.role = 'master'::text) OR ((v.organizacao_id = u.organizacao_id) AND ((v.unidade_id IS NULL) OR (v.unidade_id = u.id)))))))
  WHERE (p.id = pedido_itens.pedido_id))));


--
-- Name: pedidos; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.pedidos ENABLE ROW LEVEL SECURITY;

--
-- Name: pedidos pedidos_insert_por_vinculo; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY pedidos_insert_por_vinculo ON public.pedidos FOR INSERT WITH CHECK ((EXISTS ( SELECT 1
   FROM (public.vinculos v
     JOIN public.unidades u ON ((u.id = pedidos.unidade_id)))
  WHERE ((v.user_id = auth.uid()) AND (v.status = 'ativo'::text) AND ((v.role = 'master'::text) OR ((v.organizacao_id = u.organizacao_id) AND ((v.unidade_id IS NULL) OR (v.unidade_id = u.id))))))));


--
-- Name: pedidos pedidos_select_por_vinculo; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY pedidos_select_por_vinculo ON public.pedidos FOR SELECT USING ((EXISTS ( SELECT 1
   FROM (public.vinculos v
     JOIN public.unidades u ON ((u.id = pedidos.unidade_id)))
  WHERE ((v.user_id = auth.uid()) AND (v.status = 'ativo'::text) AND ((v.role = 'master'::text) OR ((v.organizacao_id = u.organizacao_id) AND ((v.unidade_id IS NULL) OR (v.unidade_id = u.id))))))));


--
-- Name: pedidos pedidos_update_por_vinculo; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY pedidos_update_por_vinculo ON public.pedidos FOR UPDATE USING ((EXISTS ( SELECT 1
   FROM (public.vinculos v
     JOIN public.unidades u ON ((u.id = pedidos.unidade_id)))
  WHERE ((v.user_id = auth.uid()) AND (v.status = 'ativo'::text) AND ((v.role = 'master'::text) OR ((v.organizacao_id = u.organizacao_id) AND ((v.unidade_id IS NULL) OR (v.unidade_id = u.id))))))));


--
-- Name: perfis; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.perfis ENABLE ROW LEVEL SECURITY;

--
-- Name: perfis perfis_select_mesma_unidade; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY perfis_select_mesma_unidade ON public.perfis FOR SELECT USING ((EXISTS ( SELECT 1
   FROM (public.vinculos v1
     JOIN public.vinculos v2 ON (((v2.user_id = perfis.id) AND (v2.status = 'ativo'::text))))
  WHERE ((v1.user_id = auth.uid()) AND (v1.status = 'ativo'::text) AND ((v1.role = 'master'::text) OR ((v1.organizacao_id = v2.organizacao_id) AND ((v1.unidade_id IS NULL) OR (v2.unidade_id IS NULL) OR (v1.unidade_id = v2.unidade_id))))))));


--
-- Name: perfis perfis_select_own; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY perfis_select_own ON public.perfis FOR SELECT USING ((id = auth.uid()));


--
-- Name: produtos; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.produtos ENABLE ROW LEVEL SECURITY;

--
-- Name: produtos produtos_insert_gestao; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY produtos_insert_gestao ON public.produtos FOR INSERT WITH CHECK ((EXISTS ( SELECT 1
   FROM (public.vinculos v
     JOIN public.unidades u ON ((u.id = produtos.unidade_id)))
  WHERE ((v.user_id = auth.uid()) AND (v.status = 'ativo'::text) AND ((v.role = 'master'::text) OR ((v.role = 'gestao'::text) AND (v.organizacao_id = u.organizacao_id) AND ((v.unidade_id IS NULL) OR (v.unidade_id = u.id))))))));


--
-- Name: produtos produtos_select_por_vinculo; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY produtos_select_por_vinculo ON public.produtos FOR SELECT USING ((EXISTS ( SELECT 1
   FROM (public.vinculos v
     JOIN public.unidades u ON ((u.id = produtos.unidade_id)))
  WHERE ((v.user_id = auth.uid()) AND (v.status = 'ativo'::text) AND ((v.role = 'master'::text) OR ((v.organizacao_id = u.organizacao_id) AND ((v.unidade_id IS NULL) OR (v.unidade_id = u.id))))))));


--
-- Name: produtos produtos_update_gestao; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY produtos_update_gestao ON public.produtos FOR UPDATE USING ((EXISTS ( SELECT 1
   FROM (public.vinculos v
     JOIN public.unidades u ON ((u.id = produtos.unidade_id)))
  WHERE ((v.user_id = auth.uid()) AND (v.status = 'ativo'::text) AND ((v.role = 'master'::text) OR ((v.role = 'gestao'::text) AND (v.organizacao_id = u.organizacao_id) AND ((v.unidade_id IS NULL) OR (v.unidade_id = u.id))))))));


--
-- Name: unidades; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.unidades ENABLE ROW LEVEL SECURITY;

--
-- Name: unidades unidades_select_por_vinculo; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY unidades_select_por_vinculo ON public.unidades FOR SELECT USING ((EXISTS ( SELECT 1
   FROM public.vinculos v
  WHERE ((v.user_id = auth.uid()) AND (v.status = 'ativo'::text) AND ((v.role = 'master'::text) OR ((v.organizacao_id = unidades.organizacao_id) AND ((v.unidade_id IS NULL) OR (v.unidade_id = unidades.id))))))));


--
-- Name: vinculos; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.vinculos ENABLE ROW LEVEL SECURITY;

--
-- Name: vinculos vinculos_select_own; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY vinculos_select_own ON public.vinculos FOR SELECT USING ((user_id = auth.uid()));


--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: -
--

GRANT USAGE ON SCHEMA public TO postgres;
GRANT USAGE ON SCHEMA public TO anon;
GRANT USAGE ON SCHEMA public TO authenticated;
GRANT USAGE ON SCHEMA public TO service_role;


--
-- Name: TABLE consolidados_vendas; Type: ACL; Schema: public; Owner: -
--

GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public.consolidados_vendas TO anon;
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public.consolidados_vendas TO authenticated;
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public.consolidados_vendas TO service_role;


--
-- Name: TABLE contagem_itens; Type: ACL; Schema: public; Owner: -
--

GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public.contagem_itens TO anon;
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public.contagem_itens TO authenticated;
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public.contagem_itens TO service_role;


--
-- Name: SEQUENCE contagem_itens_ordem_seq; Type: ACL; Schema: public; Owner: -
--

GRANT UPDATE ON SEQUENCE public.contagem_itens_ordem_seq TO anon;
GRANT UPDATE ON SEQUENCE public.contagem_itens_ordem_seq TO authenticated;
GRANT UPDATE ON SEQUENCE public.contagem_itens_ordem_seq TO service_role;


--
-- Name: TABLE contagens; Type: ACL; Schema: public; Owner: -
--

GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public.contagens TO anon;
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public.contagens TO authenticated;
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public.contagens TO service_role;


--
-- Name: TABLE fornecedores; Type: ACL; Schema: public; Owner: -
--

GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public.fornecedores TO anon;
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public.fornecedores TO authenticated;
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public.fornecedores TO service_role;


--
-- Name: SEQUENCE fornecedores_ordem_seq; Type: ACL; Schema: public; Owner: -
--

GRANT UPDATE ON SEQUENCE public.fornecedores_ordem_seq TO anon;
GRANT UPDATE ON SEQUENCE public.fornecedores_ordem_seq TO authenticated;
GRANT UPDATE ON SEQUENCE public.fornecedores_ordem_seq TO service_role;


--
-- Name: TABLE logs_auditoria; Type: ACL; Schema: public; Owner: -
--

GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public.logs_auditoria TO anon;
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public.logs_auditoria TO authenticated;
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public.logs_auditoria TO service_role;


--
-- Name: TABLE organizacoes; Type: ACL; Schema: public; Owner: -
--

GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public.organizacoes TO anon;
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public.organizacoes TO authenticated;
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public.organizacoes TO service_role;


--
-- Name: TABLE pedido_itens; Type: ACL; Schema: public; Owner: -
--

GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public.pedido_itens TO anon;
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public.pedido_itens TO authenticated;
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public.pedido_itens TO service_role;


--
-- Name: TABLE pedidos; Type: ACL; Schema: public; Owner: -
--

GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public.pedidos TO anon;
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public.pedidos TO authenticated;
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public.pedidos TO service_role;


--
-- Name: TABLE perfis; Type: ACL; Schema: public; Owner: -
--

GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public.perfis TO anon;
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public.perfis TO authenticated;
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public.perfis TO service_role;


--
-- Name: TABLE produtos; Type: ACL; Schema: public; Owner: -
--

GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public.produtos TO anon;
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public.produtos TO authenticated;
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public.produtos TO service_role;


--
-- Name: SEQUENCE produtos_ordem_seq; Type: ACL; Schema: public; Owner: -
--

GRANT UPDATE ON SEQUENCE public.produtos_ordem_seq TO anon;
GRANT UPDATE ON SEQUENCE public.produtos_ordem_seq TO authenticated;
GRANT UPDATE ON SEQUENCE public.produtos_ordem_seq TO service_role;


--
-- Name: TABLE unidades; Type: ACL; Schema: public; Owner: -
--

GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public.unidades TO anon;
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public.unidades TO authenticated;
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public.unidades TO service_role;


--
-- Name: TABLE vinculos; Type: ACL; Schema: public; Owner: -
--

GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public.vinculos TO anon;
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public.vinculos TO authenticated;
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public.vinculos TO service_role;


--
-- Name: DEFAULT PRIVILEGES FOR SEQUENCES; Type: DEFAULT ACL; Schema: public; Owner: -
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT UPDATE ON SEQUENCES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT UPDATE ON SEQUENCES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT UPDATE ON SEQUENCES TO service_role;


--
-- Name: DEFAULT PRIVILEGES FOR SEQUENCES; Type: DEFAULT ACL; Schema: public; Owner: -
--

ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON SEQUENCES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON SEQUENCES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON SEQUENCES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON SEQUENCES TO service_role;


--
-- Name: DEFAULT PRIVILEGES FOR FUNCTIONS; Type: DEFAULT ACL; Schema: public; Owner: -
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON FUNCTIONS TO postgres;


--
-- Name: DEFAULT PRIVILEGES FOR FUNCTIONS; Type: DEFAULT ACL; Schema: public; Owner: -
--

ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON FUNCTIONS TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON FUNCTIONS TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON FUNCTIONS TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON FUNCTIONS TO service_role;


--
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: public; Owner: -
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON TABLES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLES TO service_role;


--
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: public; Owner: -
--

ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON TABLES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON TABLES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON TABLES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON TABLES TO service_role;


--
-- PostgreSQL database dump complete
--

