-- Migração gradual do estoque: cada unidade escolhe entre a planilha legada
-- e o Postgres. O padrão continua sendo planilha para não alterar clientes
-- que ainda não passaram pela importação e conferência.
alter table unidades
add column if not exists fonte_dados_estoque text not null default 'planilha';

alter table unidades
drop constraint if exists unidades_fonte_dados_estoque_check;

alter table unidades
add constraint unidades_fonte_dados_estoque_check
check (fonte_dados_estoque in ('planilha', 'banco'));

create table if not exists produtos (
  id uuid primary key default gen_random_uuid(),
  unidade_id text not null references unidades(id),
  ordem bigint generated by default as identity,
  sku text not null,
  posicao numeric,
  grupo text not null default '',
  nome text not null default '',
  unidade_base text not null default '',
  preco_unitario numeric,
  estoque_necessario_semana numeric,
  estoque_minimo numeric,
  nome_compra text not null default '',
  unidade_embalagem_fornecedor text not null default '',
  qtd_unidade_base_por_embalagem numeric,
  preco_fornecedor numeric,
  fornecedor_1 text not null default '',
  fornecedor_2 text not null default '',
  fornecedor_3 text not null default '',
  fornecedor_4 text not null default '',
  observacoes text not null default '',
  ativo boolean not null default true,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now(),
  unique (unidade_id, sku)
);

create table if not exists fornecedores (
  id uuid primary key default gen_random_uuid(),
  unidade_id text not null references unidades(id),
  ordem bigint generated by default as identity,
  codigo text not null,
  razao_social text not null default '',
  nome_fantasia text not null default '',
  grupos text[] not null default '{}',
  nome_vendedor text not null default '',
  whatsapp text not null default '',
  condicoes_pagamento text not null default '',
  prazo_boleto text not null default '',
  limite_credito numeric,
  pedido_minimo numeric,
  dias_entrega text not null default '',
  observacoes text not null default '',
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now(),
  unique (unidade_id, codigo)
);

-- Uma contagem representa uma data da unidade. Novos envios feitos no mesmo
-- dia acrescentam itens, como o append da planilha fazia.
create table if not exists contagens (
  id uuid primary key default gen_random_uuid(),
  unidade_id text not null references unidades(id),
  data date not null,
  mes text not null,
  criado_por uuid references auth.users(id),
  criado_em timestamptz not null default now(),
  unique (unidade_id, data)
);

-- Não há unicidade por SKU: o legado permitia repetir um SKU em dois envios
-- no mesmo dia. A ordem conserva qual linha é corrigida primeiro nesse caso.
create table if not exists contagem_itens (
  id uuid primary key default gen_random_uuid(),
  contagem_id uuid not null references contagens(id) on delete cascade,
  ordem bigint generated by default as identity,
  -- Preenchido só na importação do legado. Permite repetir a importação sem
  -- duplicar linhas; novas contagens do aplicativo deixam este campo nulo.
  origem_linha_planilha integer,
  sku text not null,
  grupo text not null default '',
  nome text not null default '',
  unidade_base text not null default '',
  quantidade numeric,
  preco_unitario numeric,
  total numeric,
  alerta text not null default '',
  criado_em timestamptz not null default now(),
  unique (contagem_id, origem_linha_planilha)
);

create index if not exists produtos_unidade_ordem_idx
on produtos (unidade_id, ordem);

create index if not exists fornecedores_unidade_ordem_idx
on fornecedores (unidade_id, ordem);

create index if not exists contagens_unidade_data_idx
on contagens (unidade_id, data desc);

create index if not exists contagem_itens_contagem_ordem_idx
on contagem_itens (contagem_id, ordem);

alter table produtos enable row level security;
alter table fornecedores enable row level security;
alter table contagens enable row level security;
alter table contagem_itens enable row level security;

drop policy if exists "produtos_select_por_vinculo" on produtos;
drop policy if exists "fornecedores_select_por_vinculo" on fornecedores;
drop policy if exists "produtos_insert_gestao" on produtos;
drop policy if exists "produtos_update_gestao" on produtos;
drop policy if exists "fornecedores_insert_gestao" on fornecedores;
drop policy if exists "fornecedores_update_gestao" on fornecedores;
drop policy if exists "contagens_select_por_vinculo" on contagens;
drop policy if exists "contagens_insert_por_vinculo" on contagens;
drop policy if exists "contagem_itens_select_por_vinculo" on contagem_itens;
drop policy if exists "contagem_itens_insert_por_vinculo" on contagem_itens;
drop policy if exists "contagem_itens_update_por_vinculo" on contagem_itens;

-- Leitura do estoque: qualquer vínculo ativo que alcance a unidade.
create policy "produtos_select_por_vinculo" on produtos
  for select using (
    exists (
      select 1 from vinculos v
      join unidades u on u.id = produtos.unidade_id
      where v.user_id = auth.uid() and v.status = 'ativo'
        and (v.role = 'master' or (v.organizacao_id = u.organizacao_id and (v.unidade_id is null or v.unidade_id = u.id)))
    )
  );

create policy "fornecedores_select_por_vinculo" on fornecedores
  for select using (
    exists (
      select 1 from vinculos v
      join unidades u on u.id = fornecedores.unidade_id
      where v.user_id = auth.uid() and v.status = 'ativo'
        and (v.role = 'master' or (v.organizacao_id = u.organizacao_id and (v.unidade_id is null or v.unidade_id = u.id)))
    )
  );

-- Cadastro e preço são exclusivos de Gestão/master também no banco.
create policy "produtos_insert_gestao" on produtos
  for insert with check (
    exists (
      select 1 from vinculos v
      join unidades u on u.id = produtos.unidade_id
      where v.user_id = auth.uid() and v.status = 'ativo'
        and (v.role = 'master' or (v.role = 'gestao' and v.organizacao_id = u.organizacao_id and (v.unidade_id is null or v.unidade_id = u.id)))
    )
  );

create policy "produtos_update_gestao" on produtos
  for update using (
    exists (
      select 1 from vinculos v
      join unidades u on u.id = produtos.unidade_id
      where v.user_id = auth.uid() and v.status = 'ativo'
        and (v.role = 'master' or (v.role = 'gestao' and v.organizacao_id = u.organizacao_id and (v.unidade_id is null or v.unidade_id = u.id)))
    )
  );

create policy "fornecedores_insert_gestao" on fornecedores
  for insert with check (
    exists (
      select 1 from vinculos v
      join unidades u on u.id = fornecedores.unidade_id
      where v.user_id = auth.uid() and v.status = 'ativo'
        and (v.role = 'master' or (v.role = 'gestao' and v.organizacao_id = u.organizacao_id and (v.unidade_id is null or v.unidade_id = u.id)))
    )
  );

create policy "fornecedores_update_gestao" on fornecedores
  for update using (
    exists (
      select 1 from vinculos v
      join unidades u on u.id = fornecedores.unidade_id
      where v.user_id = auth.uid() and v.status = 'ativo'
        and (v.role = 'master' or (v.role = 'gestao' and v.organizacao_id = u.organizacao_id and (v.unidade_id is null or v.unidade_id = u.id)))
    )
  );

-- Contagem continua aberta para Gestão e Operacional.
create policy "contagens_select_por_vinculo" on contagens
  for select using (
    exists (
      select 1 from vinculos v
      join unidades u on u.id = contagens.unidade_id
      where v.user_id = auth.uid() and v.status = 'ativo'
        and (v.role = 'master' or (v.organizacao_id = u.organizacao_id and (v.unidade_id is null or v.unidade_id = u.id)))
    )
  );

create policy "contagens_insert_por_vinculo" on contagens
  for insert with check (
    exists (
      select 1 from vinculos v
      join unidades u on u.id = contagens.unidade_id
      where v.user_id = auth.uid() and v.status = 'ativo'
        and (v.role = 'master' or (v.organizacao_id = u.organizacao_id and (v.unidade_id is null or v.unidade_id = u.id)))
    )
  );

create policy "contagem_itens_select_por_vinculo" on contagem_itens
  for select using (
    exists (
      select 1 from contagens c
      join unidades u on u.id = c.unidade_id
      join vinculos v on v.user_id = auth.uid() and v.status = 'ativo'
        and (v.role = 'master' or (v.organizacao_id = u.organizacao_id and (v.unidade_id is null or v.unidade_id = u.id)))
      where c.id = contagem_itens.contagem_id
    )
  );

create policy "contagem_itens_insert_por_vinculo" on contagem_itens
  for insert with check (
    exists (
      select 1 from contagens c
      join unidades u on u.id = c.unidade_id
      join vinculos v on v.user_id = auth.uid() and v.status = 'ativo'
        and (v.role = 'master' or (v.organizacao_id = u.organizacao_id and (v.unidade_id is null or v.unidade_id = u.id)))
      where c.id = contagem_itens.contagem_id
    )
  );

create policy "contagem_itens_update_por_vinculo" on contagem_itens
  for update using (
    exists (
      select 1 from contagens c
      join unidades u on u.id = c.unidade_id
      join vinculos v on v.user_id = auth.uid() and v.status = 'ativo'
        and (v.role = 'master' or (v.organizacao_id = u.organizacao_id and (v.unidade_id is null or v.unidade_id = u.id)))
      where c.id = contagem_itens.contagem_id
    )
  );
